version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: luckydraw_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: luckydraw_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: luckydraw_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: luckydraw
      MYSQL_ROOT_PASSWORD: L0cky7_S3cur3_Root_99
      MYSQL_USER: luckydraw
      MYSQL_PASSWORD: L0cky7_S3cur3_Pass_99
    # Removed public port 3307 to block hackers.
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: luckydraw_redis
    ports:
      - "6379:6379"

volumes:
  mysqldata: